import React, { useState, useCallback, useMemo } from 'react';
import { BrainCircuit, Copy, CheckCircle2, PlayCircle, Download, FileText, FileJson, FileType } from 'lucide-react';
import { GeneratedScript, Tone } from './types';
import { DEFAULT_SCRIPT } from './constants';
import { generateScript } from './services/geminiService';
import { ScriptSegmentCard } from './components/ScriptSegmentCard';
import { InputForm } from './components/InputForm';

const App: React.FC = () => {
  const [script, setScript] = useState<GeneratedScript>(DEFAULT_SCRIPT);
  const [topic, setTopic] = useState<string>('');
  const [tone, setTone] = useState<Tone>(Tone.URGENT);
  const [duration, setDuration] = useState<number>(45);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState<boolean>(false);

  const handleGenerate = useCallback(async () => {
    if (!topic.trim()) return;
    
    setLoading(true);
    setError(null);
    try {
      const newScript = await generateScript(topic, tone, duration);
      setScript(newScript);
    } catch (err) {
      setError("Failed to generate script. Please check your API key and try again.");
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, [topic, tone, duration]);

  const handleCopy = useCallback(() => {
    const text = script.segments
      .map(s => `[${s.startTime}-${s.endTime}s] ${s.label}\nAUDIO: "${s.text}"\nVISUAL: [${s.visual}]`)
      .join('\n\n');
    
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [script]);

  const downloadScript = useCallback((format: 'txt' | 'md' | 'json') => {
    if (!script) return;
    
    let content = '';
    let mimeType = '';
    let extension = '';
    const filename = (script.topic || 'script').replace(/[^a-z0-9]/gi, '-').toLowerCase();

    if (format === 'json') {
        content = JSON.stringify(script, null, 2);
        mimeType = 'application/json';
        extension = 'json';
    } else if (format === 'md') {
         content = `# ${script.topic}\n\n`;
         content += `**Total Duration:** ${duration}s\n`;
         content += `**Tone:** ${tone}\n\n`;
         script.segments.forEach(s => {
            content += `## [${s.startTime}s-${s.endTime}s] ${s.label}\n`;
            content += `**Audio:** ${s.text}\n\n`;
            content += `> **Visual:** ${s.visual}\n\n`;
         });
         mimeType = 'text/markdown';
         extension = 'md';
    } else {
         content = `TITLE: ${script.topic}\n`;
         content += `DURATION: ${duration}s\n`;
         content += `TONE: ${tone}\n\n`;
         script.segments.forEach(s => {
            content += `[${s.startTime}s-${s.endTime}s] ${s.label}\n`;
            content += `AUDIO: ${s.text}\n`;
            content += `VISUAL: ${s.visual}\n\n`;
         });
         mimeType = 'text/plain';
         extension = 'txt';
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${filename}.${extension}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }, [script, tone, duration]);

  const handleShare = useCallback((platform: 'twitter' | 'email') => {
    const textStr = script.segments
      .map(s => `[${s.label}]: ${s.text}`)
      .join('\n\n');
    
    if (platform === 'twitter') {
      // Twitter truncates content, so we share a teaser
      const tweetText = `Just generated a viral neuroscience-backed script about "${script.topic}"!\n\nHook: "${script.segments[0].text}"\n\n#ContentCreator #ScriptGen`;
      window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(tweetText)}`, '_blank');
    } else if (platform === 'email') {
      const subject = `Script Draft: ${script.topic}`;
      const body = `Here is the YouTube Short script for "${script.topic}":\n\n${textStr}\n\nGenerated by NeuroViral ScriptGen`;
      window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    }
  }, [script]);

  // Calculate actual total duration from the script segments
  const currentDuration = useMemo(() => {
    if (!script.segments.length) return 0;
    const lastSegment = script.segments[script.segments.length - 1];
    return lastSegment.endTime;
  }, [script]);

  return (
    <div className="min-h-screen bg-slate-950 flex flex-col items-center p-4 sm:p-8 font-sans">
      
      {/* Header */}
      <header className="w-full max-w-3xl mb-10 text-center space-y-4 pt-8">
        <div className="inline-flex items-center justify-center p-3 bg-indigo-500/10 rounded-2xl mb-2 ring-1 ring-indigo-500/20">
          <BrainCircuit className="w-8 h-8 text-indigo-400" />
        </div>
        <h1 className="text-4xl sm:text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-b from-white to-slate-400 tracking-tight">
          NeuroViral <span className="text-indigo-500">ScriptGen</span>
        </h1>
        <p className="text-slate-400 text-lg max-w-xl mx-auto leading-relaxed">
          Generate high-retention YouTube Short scripts based on neuroscience principles. 
          <br className="hidden sm:block"/>
          Hook. Problem. Solution. Demo. CTA.
        </p>
      </header>

      {/* Main Content */}
      <main className="w-full max-w-3xl">
        
        <InputForm 
          topic={topic} 
          setTopic={setTopic} 
          tone={tone} 
          setTone={setTone} 
          duration={duration}
          setDuration={setDuration}
          onGenerate={handleGenerate}
          isLoading={loading}
        />

        {error && (
          <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-4 rounded-xl mb-8 text-center">
            {error}
          </div>
        )}

        {/* Output Section */}
        <div className="relative">
          {/* Action Bar */}
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-6 px-2 gap-4">
            <h2 className="text-xl font-bold text-white flex items-center">
              <PlayCircle className="w-5 h-5 mr-2 text-indigo-400" />
              Current Script: <span className="text-indigo-300 ml-2 font-normal truncate max-w-[200px]">{script.topic}</span>
            </h2>
            
            <div className="flex items-center gap-3 w-full sm:w-auto">
              {/* Export Group */}
              <div className="flex items-center bg-slate-900 rounded-lg p-1 border border-slate-800">
                 <button 
                    onClick={() => downloadScript('txt')} 
                    className="p-2 text-slate-400 hover:text-white hover:bg-slate-800 rounded-md transition-colors"
                    title="Export as Text"
                 >
                    <FileText className="w-4 h-4" />
                 </button>
                 <div className="w-px h-4 bg-slate-800 mx-1"></div>
                 <button 
                    onClick={() => downloadScript('md')} 
                    className="p-2 text-slate-400 hover:text-white hover:bg-slate-800 rounded-md transition-colors"
                    title="Export as Markdown"
                 >
                    <FileType className="w-4 h-4" />
                 </button>
                 <div className="w-px h-4 bg-slate-800 mx-1"></div>
                 <button 
                    onClick={() => downloadScript('json')} 
                    className="p-2 text-slate-400 hover:text-white hover:bg-slate-800 rounded-md transition-colors"
                    title="Export as JSON"
                 >
                    <FileJson className="w-4 h-4" />
                 </button>
              </div>

              <button 
                onClick={handleCopy}
                className="flex-1 sm:flex-none flex items-center justify-center space-x-2 text-sm font-medium text-slate-400 hover:text-white transition-colors bg-slate-900 hover:bg-slate-800 px-4 py-2 rounded-lg border border-slate-800 h-[42px]"
              >
                {copied ? (
                  <>
                    <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                    <span className="text-emerald-400">Copied</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4" />
                    <span>Copy</span>
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Timeline Container */}
          <div className="bg-slate-950/50 rounded-3xl p-2 sm:p-8 border border-slate-800/50 shadow-2xl shadow-indigo-500/5">
            <div className="ml-4 sm:ml-2">
              {script.segments.map((segment, index) => (
                <ScriptSegmentCard 
                  key={index} 
                  segment={segment} 
                  isLast={index === script.segments.length - 1}
                  tone={tone}
                  onShare={handleShare}
                />
              ))}
            </div>
          </div>

          <div className="mt-8 text-center text-slate-600 text-xs font-mono">
             TOTAL DURATION: {currentDuration}s • OPTIMIZED FOR RETENTION
          </div>
        </div>

      </main>
    </div>
  );
};

export default App;